steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'USE_RELEASED_VERSION=${_USE_RELEASED_VERSION}'
  - '--build-arg'
  - 'CLIENT_BRANCH=${_CLIENT_BRANCH}'
  - '--build-arg'
  - 'CLIENT_REPO=${_CLIENT_REPO}'
  - '--build-arg'
  - 'COMPILE_RUST_ADDON=${_COMPILE_RUST_ADDON}'
  - '--build-arg'
  - 'COMPILE_GO_ADDON=${_COMPILE_GO_ADDON}'
  - '--target=${_DOCKER_TARGET}'
  - '-t'
  - '${_IMAGE_NAME}'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_IMAGE_NAME}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    TERMINATION_FLAG=""
    if [ "${_TERMINATION_ACTION}" != "STOP" ]; then
      TERMINATION_FLAG="--instance-termination-action=${_TERMINATION_ACTION}"
    fi

    gcloud compute instances create-with-container "${_JOB_NAME}" \
      --container-image="${_IMAGE_NAME}" \
      --project="${PROJECT_ID}" \
      --zone="${_ZONE}" \
      --machine-type="${_MACHINE_TYPE}" \
      --no-address \
      --scopes="cloud-platform" \
      --service-account="spanner-client-benchmarks@${PROJECT_ID}.iam.gserviceaccount.com" \
      --provisioning-model="${_PROVISIONING_MODEL}" \
      $$TERMINATION_FLAG \
      --container-restart-policy=never \
      --boot-disk-size=50GB \
      --labels=owner=spanner-client-benchmarks \
      --metadata="DEBUG_VM=${_DEBUG_VM}" \
      ${_GCE_ENV_FLAGS} \
      ${_GCE_CONTAINER_ARGS} \
      --metadata-from-file="startup-script=gce_startup.sh"

images:
- '${_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROVISIONING_MODEL: 'SPOT'
  _TERMINATION_ACTION: 'DELETE'
  _DEBUG_VM: 'false'
  _DOCKER_TARGET: 'release'
