name: Channel Scaling Bursty Benchmarks

on:
  schedule:
    # Run daily at 08:30 UTC
    - cron: '30 8 * * *'
  workflow_dispatch:
    inputs:
      for_alerting:
        description: 'Mark metrics for alerting'
        required: false
        type: boolean
        default: false

jobs:
  run-point-select-multi-core:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      clients: '["java", "go", "rust"]'
      benchmark_types: '["point-select"]'
      duration: '1h'
      load_type: 'spiky'
      tps: '2000'
      threads: '500'
      burst_factor: '3.8'
      burst_duration: '5.0'
      burst_fraction: '0.25'
      cpu: '4'
      memory: '4Gi'
      use_sidecar: 'true'
      spanner_num_channels: '16'
      benchmark_name: 'channel-scaling-bursty-point-select'
      for_alerting: "${{ github.event_name == 'schedule' || inputs.for_alerting == true || inputs.for_alerting == 'true' }}"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  run-point-select-single-core:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      clients: '["node", "python"]'
      benchmark_types: '["point-select"]'
      duration: '1h'
      load_type: 'spiky'
      tps: '600'
      threads: '100'
      burst_factor: '3.0'
      burst_duration: '5.0'
      burst_fraction: '0.25'
      cpu: '4'
      memory: '4Gi'
      use_sidecar: 'true'
      benchmark_name: 'channel-scaling-bursty-point-select'
      for_alerting: "${{ github.event_name == 'schedule' || inputs.for_alerting == true || inputs.for_alerting == 'true' }}"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  run-select-update-multi-core:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      clients: '["java", "go", "rust"]'
      benchmark_types: '["select-update"]'
      duration: '1h'
      load_type: 'spiky'
      tps: '2000'
      threads: '500'
      burst_factor: '3.8'
      burst_duration: '5.0'
      burst_fraction: '0.25'
      cpu: '4'
      memory: '4Gi'
      use_sidecar: 'true'
      spanner_num_channels: '16'
      benchmark_name: 'channel-scaling-bursty-select-update'
      for_alerting: "${{ github.event_name == 'schedule' || inputs.for_alerting == true || inputs.for_alerting == 'true' }}"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  run-select-update-single-core:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      clients: '["node", "python"]'
      benchmark_types: '["select-update"]'
      duration: '1h'
      load_type: 'spiky'
      tps: '100'
      threads: '80'
      burst_factor: '3.0'
      burst_duration: '5.0'
      burst_fraction: '0.25'
      cpu: '4'
      memory: '4Gi'
      use_sidecar: 'true'
      benchmark_name: 'channel-scaling-bursty-select-update'
      for_alerting: "${{ github.event_name == 'schedule' || inputs.for_alerting == true || inputs.for_alerting == 'true' }}"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
