name: Large Result Set Benchmarks

on:
  schedule:
    - cron: "47 17 * * *"
  workflow_dispatch:
    inputs:
      for_alerting:
        description: "Mark metrics for alerting"
        required: false
        type: boolean
        default: false

jobs:
  run:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      benchmark_types: '["read-large-result-set", "read-narrow-result-set"]'
      duration: "1h"
      load_type: "closed-loop"
      threads: "1"
      cpu: "2"
      for_alerting: "${{ github.event_name == 'schedule' || inputs.for_alerting == true || inputs.for_alerting == 'true' }}"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
