name: Large Result Set Benchmarks

on:
  schedule:
    - cron: '47 17 * * *'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      benchmark_types: '["read-large-result-set"]'
      duration: '1h'
      disable_builtin_metrics: 'true'
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
