name: Schedule Latency Benchmarks

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/benchmark-template.yml
    with:
      benchmark_types: '["point-select", "select-update"]'
      duration: '2h'
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
